### ISSUE TITLE
It's pointless 

### ISSUE THREAD

**Issue by thedenisnikulin** [crablang/crab#14] opened 2023-04-14 15:06 UTC
Rather than being escapist and just avoid problems by forking Rust (which itself brings a ton of problems), we better wait for the trademark policy draft to be improved. We have all the power to decide what the policy will eventually be, and we all can participate in this by suggesting improvements. Yes, the first draft is stupid and even disrespectful to all people who put a lot of effort in Rust programming language, but there's no point in panicking and straight away rolling out a whole separate project.

It's all fun, ha-ha, we have our own programming language, look Rust Foundation, we can live without you, we have power, ha-ha, but it's not rational. Early panicking will lead to nothing but more conflicts and polarization in our community. I love Rust community and would not like to see this happen.

**Comment by dogue** [comment] 2023-04-14 15:08
I think you misunderstand the purpose of this project.

**Comment by TCROC** [comment] 2023-04-14 15:18
The project serves a few purposes in my mind.

1. Obviously to show our disagreement of the trademark policy.
2. An alternative that keeps up to date with upstream Rust but does not impose any restrictions in usage.  That means terminology, icons, etc. of crab can be used as freely as possible.
3. A place where people feel safe from litigious matters.  We want to do cool computer stuff.  We aren't lawyers and law is scary.

I'm sure something will be put out on our website clarifying what the repo is attempting to accomplish.  This is merely what it means to me.

**Comment by JiveyGuy** [comment] 2023-04-14 16:12
> The project serves a few purposes in my mind.
> 
> 1. Obviously to show our disagreement of the trademark policy.
> 2. An alternative that keeps up to date with upstream Rust but does not impose any restrictions in usage.  That means terminology, icons, etc. of crab can be used as freely as possible.
> 3. A place where people feel safe from litigious matters.  We want to do cool computer stuff.  We aren't lawyers and law is scary.
> 
> I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.
> 
> Edit: change 'our website' to 'the website'

As far as keeping up to date, does that mean we are going to pull changes from the *redacted* repo and keep this as a mirror of it?

**Comment by pauschuu** [comment] 2023-04-14 16:23
> 1. Obviously to show our disagreement of the trademark policy.

> I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.

This would be a great opportunity to summarize what the problem with the trademark policy exactly is. I have not followed this at all and many other people who use Rust probably also don't know what the fuzz is about...

**Comment by TCROC** [comment] 2023-04-14 16:59
> > The project serves a few purposes in my mind.
> > 
> > 1. Obviously to show our disagreement of the trademark policy.
> > 2. An alternative that keeps up to date with upstream Rust but does not impose any restrictions in usage.  That means terminology, icons, etc. of crab can be used as freely as possible.
> > 3. A place where people feel safe from litigious matters.  We want to do cool computer stuff.  We aren't lawyers and law is scary.
> > 
> > I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.
> > Edit: change 'our website' to 'the website'
> 
> As far as keeping up to date, does that mean we are going to pull changes from the _redacted_ repo and keep this as a mirror of it?

I think there is talk in the Discord of automating it

**Comment by TCROC** [comment] 2023-04-14 19:15
> > 1. Obviously to show our disagreement of the trademark policy.
> 
> > I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.
> 
> This would be a great opportunity to summarize what the problem with the trademark policy exactly is. I have not followed this at all and many other people who use Rust probably also don't know what the fuzz is about...

I think ThePrimeagen did a pretty good job of that! :)

https://youtu.be/gutR_LNoZw0

**Comment by LouisGariepy** [comment] 2023-04-14 19:40
> The project serves a few purposes in my mind.
> 
>     1. Obviously to show our disagreement of the trademark policy.
> 
>     2. An alternative that keeps up to date with upstream Rust but does not impose any restrictions in usage.  That means terminology, icons, etc. of crab can be used as freely as possible.
> 
>     3. A place where people feel safe from litigious matters.  We want to do cool computer stuff.  We aren't lawyers and law is scary.
> 
> 
> I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.
> 
> Edit: change 'our website' to 'the website'

Regarding 2, the trademark policy does not affect the Rust language whatsoever. The Rust foundation does not hold the rights to the language in any case. **We as a community could create our own logos and terminology for rust that is not subject to the trademark policy** without going through "creating" a new language. This seems like an unnecessary step that doesn't actually do any good for the community.

Regarding 3, it seems ironic to me since you say that "you just want to do cool computer stuff", and yet you are putting effort into something that is very much not "cool computer stuff", just so you can avoid a trademark policy that most likely doesn't affect you all that much. Why not just do the cool stuff and skip the scary legal stuff instead of doing this?

Or, if it does affect you in a meaningful way, why not fill the feedback form and wait for the the foundation to respond to the feedback (like they have said they will https://blog.rust-lang.org/inside-rust/2023/04/12/trademark-policy-draft-feedback.html). Seems very unproductive to go nuclear while we don't even have the final trademark policy yet.

Cheers! I hope someone is willing to discuss this instead of just going full echo chamber.

**Comment by TCROC** [comment] 2023-04-14 19:52
> > The project serves a few purposes in my mind.
> > ```
> > 1. Obviously to show our disagreement of the trademark policy.
> > 
> > 2. An alternative that keeps up to date with upstream Rust but does not impose any restrictions in usage.  That means terminology, icons, etc. of crab can be used as freely as possible.
> > 
> > 3. A place where people feel safe from litigious matters.  We want to do cool computer stuff.  We aren't lawyers and law is scary.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm sure something will be put out on the website clarifying what the repo is attempting to accomplish. This is merely what it means to me.
> > Edit: change 'our website' to 'the website'
> 
> Regarding 2, the trademark policy does not affect the Rust language whatsoever. The Rust foundation does not hold the rights to the language in any case. As for the word marks and logos, **we as a community could create our own logos and terminology for rust that is not subject to the trademark policy** without going through "creating" a new language. This seems like an unnecessary step that doesn't actually do any good for the community.
> 
> Regarding 3, it seems ironic to me since you say that "you just want to do cool computer stuff", and yet you are putting effort into something that is very much not "cool computer stuff", just so you can avoid a trademark policy that most likely doesn't affect you all that much. Why not just do the cool stuff and skip the scary legal stuff instead of doing this?
> 
> Or, if it does affect you in a meaningful way, why not fill the feedback form and wait for the the foundation to respond to the feedback (like they have said they will https://blog.rust-lang.org/inside-rust/2023/04/12/trademark-policy-draft-feedback.html). Seems very unproductive to go nuclear while we don't even have the final trademark policy yet.
> 
> Cheers! I hope someone is willing to discuss this instead of just going full echo chamber.

Absolutely!  This is great discussion!  And I have personally already filled out the feedback form.  I could also add a point 4 to my reasons:

The fact that The Rust Foundation even thought that was reasonably close to a draft to show the community demonstrated to me that they are completely disconnected between directions that the community wants to go and the direction they (The Foundation) wants to go.

"Want" being the key word.

I've used the analogy of "we wanted a blueprint for a house for a family and 2 bedrooms" and they gave us a blueprint "for an underground bunker".

It crushed trust for me and many others.  We feel that we need a project that keeps community priorities as the top priority.

And I think its pretty much just 1 priority (at least that I'm personally concerned with) and that is freedom.  No bureaucracy.  No rules in regards to the language, trademark, tools, or anything of that nature.

**Comment by TCROC** [comment] 2023-04-14 19:53
And its not necessarily a "new language" per say.  Its more of a "rebranded language".  At least that's what it currently is.

**Comment by TCROC** [comment] 2023-04-14 19:55
The current plan is to keep it in sync with upstream Rust

**Comment by LouisGariepy** [comment] 2023-04-14 20:10
> The fact that The Rust Foundation even thought that was reasonably close to a draft to show the community demonstrated to me that they are completely disconnected between directions that the community wants to go and the direction they (The Foundation) wants to go.

@TCROC Thank you for your response, I appreciate it :)

I think you got that backwards. Rust has already been trademarked for a very, very long time. That trademark was filed by Mozilla. The fact that the foundation is willing to consult the community on the policy shows that *they do care* about what we have to say. Instead of going full on "**how dare they**", you should point out specific grievances that affect you personally. Let's be pragmatic instead of dogmatic.

> And I think its pretty much just 1 priority (at least that I'm personally concerned with) and that is freedom. No bureaucracy. No rules in regards to the language, trademark, tools, or anything of that nature.

I think this is a misunderstanding of what the trademark is actually for. The goal is not to restrict the average user (remember that trademark holders are not obligated to sue any particular infraction, and it's very unlikely that the Rust Foundation will ever exert that right on grass-roots users). How would you feel about a shady company posturing as "The Official Rust" distributing a paid copy of the compiler? Does that seems like a thing we as a community should allow? That's what the trademark policy is for.

Also, you haven't really responded to: why not use the terms CrabLang (instead of RustLang) and Ferris (instead of the logo), instead of actually forking the language? What good does it do? It's not like the Foundation has any jurisdiction over you besides the trademarks, so the "bureaucracy" argument is strange to me.

**Comment by TCROC** [comment] 2023-04-14 20:19
> @TCROC Thank you for your response, I appreciate it :)
> 
> > The fact that The Rust Foundation even thought that was reasonably close to a draft to show the community demonstrated to me that they are completely disconnected between directions that the community wants to go and the direction they (The Foundation) wants to go.
> 
> I think you got that backwards. Rust has already been trademarked for a very, very long time. That trademark was filed by Mozilla. The fact that the foundation is willing to consult the community on the policy shows that _they do care_ about what we have to say. Instead of going full on "**how dare they**", you should point out specific grievances that affect you personally. Let's be pragmatic instead of dogmatic.
> 
> > And I think its pretty much just 1 priority (at least that I'm personally concerned with) and that is freedom. No bureaucracy. No rules in regards to the language, trademark, tools, or anything of that nature.
> 
> I think this is a misunderstanding of what the trademark is actually for. The goal is not to restrict the average user (remember that trademark holders are not obligated to sue any particular infraction, and it's very unlikely that the Rust Foundation will ever exert that right on grass-roots users). How would you feel about a shady company posturing as "The Official Rust" distributing a paid copy of the compiler? Does that seems like a thing we as a community should allow? That's what the trademark policy is for.
> 
> Also, you haven't really responded to: why not use the terms CrabLang (instead of RustLang) and Ferris (instead of the logo), instead of actually forking the language? What good does it do? It's not like the Foundation has any jurisdiction over you besides the trademarks, so the "bureaucracy" argument is strange to me.

So I appreciate that they consulted with us.  I really do.  Its the fact that they wanted that as their first draft.  That they didn't see and fix those issues first.  The people who are supposed to be our representatives and supporters are so out of touch that they were blind to the fact that the draft goes against A LOT of what we stand for.  The extreme restrictions on domain names, inserting politically divisive topics, locking down what can be used in vocabulary regarding nouns and verbs, the logo cannot be colored, etc.

It was very restrictive and against what I want when I use a programming language and engage in a community.

I'm less concerned with bad actors and impersonators.  If somebody wants to pretend to be officially sponsored by CrabLang, great!  If they want to claim to be the creator of CrabLang, go for it!  I'll deny it if its not true and anyone asks.  Either way I'm not bothered by it.

**Comment by TCROC** [comment] 2023-04-14 20:22
Being concerned about whether I used the term Rust correctly in my sentence, whether or not I put a disclosure in my book or blog, whether or not the logo is sized correctly on my website.

That is stressful for me and I imagine many others.

**Comment by TCROC** [comment] 2023-04-14 20:26
And its not that I'm impatient and won't wait for the final draft.  I just don't trust the Foundation because that is what I interpreted them as wanting.  And they have quite a bit of power and influence to push for their wants.

**Comment by LouisGariepy** [comment] 2023-04-14 20:32
> The extreme restrictions on domain names, inserting politically divisive topics, locking down what can be used in vocabulary regarding nouns and verbs, the logo cannot be colored, [...], being concerned about whether I used the term Rust correctly in my sentence, whether or not I put a disclosure in my book or blog, whether or not the logo is sized correctly on my website.
>
> It was very restrictive and against what I want when I use a programming language and engage in a community.

I agree, which is why it's important to make sure the policy gets addressed in a satisfactory manner.

> I'm less concerned with bad actors and impersonators. 

So you're not concerned about your users getting potentially scammed, hacked, or misled in some other way? That doesn't seem like a very nice community to me...

>  I just don't trust the Foundation because that is what I interpreted them as wanting. And they have quite a bit of power and influence to push for their wants.

That is just conspiratorial at best. there a lot of decent people in the foundation. Remember they are actual real people, with unique feelings and desires. It's not like the Foundation is one monolithic entity that only wants to deprive you of your rights...

Finally, and for the third time: you are *already* abiding by the trademark policy by using custom terms and logos. Why not keep doing the same on your blog, website or whatever? Just use Ferris and Crab, then you're golden. And that seems to be what you want to do anyway, so what's the problem? Genuinely asking.

**Comment by TCROC** [comment] 2023-04-14 20:50
> I agree, which is why it's important to make sure the policy gets addressed in a satisfactory manner.

I also agree to this point

> So you're not concerned about your users getting potentially scammed, hacked, or misled in some other way? That doesn't seem like a very nice community to me...

I don't view anyone as being "my" user.  Nor do I want to be viewed as being "someone else's" user and them feel some need to restrict me for my protection.  I want to be free to do as I choose and I want others to be free to do as they choose.

> That is just conspiratorial at best. there a lot of decent people in the foundation. Remember they are actual real people, with unique feelings and desires. It's not like the Foundation is one monolithic entity that only wants to deprive you of your rights...

I'm not attacking anyone.  I've actually talked to these people and they were very friendly.  I enjoyed talking to them and I hope we can still collaborate on projects together. We seemed to just have incompatible views towards what we thought Rust was and what we wanted Rust to be.

> Again, and for the third time: you are already abiding by the trademark policy by using custom terms and logos. Why not keep doing the same on your blog, website or whatever? Just use Ferris and Crab, then you're golden. And that seems to be what you want to do anyway, so what's the problem? Genuinely asking.

Because Ferris is compatible with what we want CrabLang to be :)

**Comment by LouisGariepy** [comment] 2023-04-14 21:03
> Because Ferris is compatible with what we want CrabLang to be :)

But Ferris is already compatible with what Rust is. You can use it freely as you want. Just because the official name and logo are restricted (for some specific uses) doesn't suddenly prevent you from using your own preferred logos (or Ferris, or the word "Crab"). That's the part I don't understand. But it seems like you're not interested in answering this specific point, so I won't press anymore.

Ultimately, using this fork doesn't give back any more rights than we currently have, nor does it solve any problem with the Foundation. Forking the Rust repo doesn't change anything with regards to trademarks or whatever.

Good luck with the project! I'll just go back to writing rust code :smile:

**Comment by trvswgnr** [comment] 2023-04-14 21:27
@LouisGariepy i don't think you understand why this fork exists, and that's ok. we're not trying to supplant rust or fracture the community, and we hope the rust community will still welcome us. we simply want a version of the language that isn't connected to trademark policies put in place—in the past, present, or future—by a foundation with corporate interests.

**Comment by TCROC** [comment] 2023-04-14 21:29
@LouisGariepy 

> That's the part I don't understand.

I'm genuinely trying to answer this because it is the reason for the fork. I think you answered it with your preceding statement:

> Just because the official name and logo are restricted (for some specific uses)...

I did not know it was restricted AT ALL priory to the policy announcement. And I definitely didn't like the proposed restrictions that the foundation **wants**.

> Ultimately, using this fork doesn't give back any more rights than we currently have, nor does it solve any problem with the Foundation. Forking the Rust repo doesn't change anything with regards to trademarks or whatever.

Correct. I do not want to spend the energy fighting for rights and security from being sued that I already thought I had.

> nor does it solve any problem with the Foundation

Although I may be interested in this if I felt I would be listened to. The recent responses from the foundation and my interaction with them has not made me feel like I have much of an influence.

> Good luck with the project! I'll just go back to writing rust code 😄. Thanks for being willing to discuss this cordially.

Absolutely! I would hope for our communities to cohesively live together instead of being divided.

Just because our views are incompatible does not mean our code has to be ;)

**Comment by LouisGariepy** [comment] 2023-04-14 21:30
@trvswgnr But again that is a wild misconception. The language *is not* tied to the trademarks. Like at all.

The logos and the name *are* trademarked, but that has nothing to do with the actual code. You don't need a fork to have alternative names and logos.

**Comment by LouisGariepy** [comment] 2023-04-14 21:36
To add a bit more, I think this project should provide alternative names and logos, free to use by the community. I think that forking the repo **is** not only divisive by nature.

**Comment by TCROC** [comment] 2023-04-14 21:40
> @trvswgnr But again that is a wild misconception. The language itself (as in the code) *is not* tied to the trademarks. Like at all. The proof is that you (and many others) can and have forked the language without being legally liable.
> 
> 
> 
> The logos and the name *are* trademarked, but that has nothing to do with the actual code. You don't need a fork to have alternative names and logos. Just use whichever alternative names and logos you desire :p

Well we are making a few changes. I think we are changing the names of the applications:

rustlang -> crablang
rust -> crab
rustc -> crabc
rustfmt -> crabfmt
cargo -> crabgo 
clippy -> crabby
crates -> cakes (like crab cakes)
crates.io -> crabcakes.io

At least that's what I think the settled on changes are. It'll be official when the PRs go through.

**Comment by LouisGariepy** [comment] 2023-04-14 21:47
> we are changing the names of the applications
Why not let the code be as is, and provide free alternative names and logos so that people can choose whatever names and logos they want to use instead of being forced onto one? Isn't that what this is all about?

I definitely think you guys (as contributors/maintainers) should consider dropping the code aspect (since the Rust code is already free to use) and focusing on what the community actually want: free alternatives to names and logos.

I would wholeheartedly support such a project. I think it'd be very well received too.

**Comment by Divlo** [comment] 2023-04-14 21:53
Is the whole story about all that, similar to the VSCode and VSCodium story?

Also, if we start to name the language with different names, it will only become confusing and very weird.
Imagine some people making YouTube Videos or Blog post about Rust and others Crab, but it's actually talking about the same thing, how weird that is.

**Comment by trvswgnr** [comment] 2023-04-14 21:54
@LouisGariepy just telling people to start calling something by another name isn't effective and doesn't fully represent what we want to do. this is a fork for the community **and** it has a different name.

there's also the issue of promotion and content creation using tools and a language with trademarks.

**Comment by Divlo** [comment] 2023-04-14 21:57
> just telling people to start calling something by another name isn't effective and doesn't fully represent what we want to do. this is a fork for the community **and** it has a different name.

@trvswgnr  Hmm, then I didn't understand what you want to do. Would be nice to add in the README exactly what are the goals.
Technically speaking, is the language the same, is any Rust code will be compatible with Crab and vice-versa?
Or Crab will get special features/treatments for some things?

**Comment by LouisGariepy** [comment] 2023-04-14 21:58
It was said earlier that Crab would mirror the Rust repo (in some way or another).

It's very hard to argue that you don't intend to fracture the community if you're intending on modifying the compiler itself...

**Comment by TCROC** [comment] 2023-04-14 22:00
> > we are changing the names of the applications
> 
> 
> 
> Why not let the code be as is, and provide free alternative names and logos so that people can choose whatever names and logos they want to use instead of being forced onto one? Isn't that what this is all about?
> 
> 
> 
> I definitely think you guys (as contributors/maintainers) should consider dropping the code aspect (since the Rust code is already free to use) and focus on what the community actually wants: free alternatives to names and logos.
> 
> 
> 
> I would wholeheartedly support such a project. I think it'd be very well received too.

That is what we are doing. We are currently stripping out the things Rust Foundation wants control over. If they want it they can have it. This will ensure we don't step on their toes.

And it gives other people that use CrabLang the reassurance they also aren't stepping on anyone's toes, ever having anything taken away from them, or having any ideals forced upon them by using CrabLang.

**Comment by TCROC** [comment] 2023-04-14 22:02
So I feel like what u just proposed is exactly what we are doing

**Comment by LouisGariepy** [comment] 2023-04-14 22:03
> And it gives other people that use CrabLang the reassurance they also aren't stepping on anyone's toes

That is false. Since you don't intend to trademark your brand, I could register a trademark for CrabLang and Cease and Desist you, which is part of why Rust is trademarked at all.

> So I feel like what u just proposed is exactly what we are doing

What I'm proposing is to 1) Not fork the compiler, and 2) focus on providing alternative names and logos that the community is free to use.

**Comment by Divlo** [comment] 2023-04-14 22:04
> It was said earlier that Crab would mirror the Rust repo (in some way or another).
> 
> It's very hard to argue that you don't intend to fracture the community if you're intending on modifying the compiler's code itself...

If the langage is technically the same, and it's called with another name and logo.
But still it's not about only changing the name, and it doesn't fully represent what you want to do.

I'm sorry, I'm lost, I don't get it. :sweat_smile: 
What is the things you want to do then?
> fully represent what we want to do

**Comment by TCROC** [comment] 2023-04-14 22:21
I think @trvswgnr clarified up above that there are in fact larger goals in mind with the fork than just a rename. I'm excited to see and am on board with CrustLang.

**Comment by LouisGariepy** [comment] 2023-04-14 22:46
So much for that!

> And its not necessarily a "new language" per say. Its more of a "rebranded language". At least that's what it currently is.

> Just because our views are incompatible does not mean our code has to be ;)

> we're not trying to supplant rust or fracture the community

It's one thing to make a protest fork, but it seems more and more like a hostile fork. If the code is incompatible, then the community will be fractured.

**Comment by TCROC** [comment] 2023-04-14 23:30
> So much for that!
> 
> 
> 
> > And its not necessarily a "new language" per say. Its more of a "rebranded language". At least that's what it currently is.
> 
> 
> 
> > Just because our views are incompatible does not mean our code has to be ;)
> 
> 
> 
> > we're not trying to supplant rust or fracture the community
> 
> 
> 
> It's one thing to make a protest fork, but it seems more and more like a hostile fork. If the code is incompatible, then the community will be fractured.

It's not a hostile fork. Nothing hostile is planned. I expect rust and crab will be able to exist cohesively. 

It's just more than a rename of the repo. 

Up above I listed some of the applications being renamed but those are just user-facing front end interfaces. Nothing code breaking.

I imagine it's just more things like that.

Purging the things Rust Foundation wants concrete control over.

**Comment by TCROC** [comment] 2023-04-14 23:45
@LouisGariepy @Divlo 

It's being discussed over here:

https://github.com/crablang/crab/issues/12

**Comment by TCROC** [comment] 2023-04-15 03:42
@LouisGariepy @Divlo 

@trvswgnr has confirmed that we will maintain upstream compatibility. So no need to worry about fracturing the community:

https://github.com/crablang/crab/issues/12#issuecomment-1509452062

Although we might still play around with experimental languages under different repos / branches! :)

**Comment by BrentBoyMeBob** [comment] 2023-04-15 03:49
With all due respect to the project, I have a few questions.
a. What is the usecase here? Unless this is mostly cross-compatible as a libre or detoxed version of sorts, or like a stripped version of rustc, I don't know what the use would be.
b. Is this a long-term fork? I feel as if this is like the Audacity fork situation all over again, where Tenacity and Sneedacity would exist for a bit as decorpo'd forks before dropping dead after no one cared.

**Comment by TCROC** [comment] 2023-04-15 04:08
> With all due respect to the project, I have a few questions.
> 
> a. What is the usecase here? Unless this is mostly cross-compatible as a libre or detoxed version of sorts, or like a stripped version of rustc, I don't know what the use would be.
> 
> b. Is this a long-term fork? I feel as if this is like the Audacity fork situation all over again, where Tenacity and Sneedacity would exist for a bit as decorpo'd forks before dropping dead.

This is what it is to me: https://github.com/crablang/crab/issues/14#issuecomment-1508776721

With more details throughout the issue. I've been pretty active in responding on this one.

I believe a website will be updated soon with further clarification of the project as a whole.

From my interaction with everyone, I get the sense that it's long term.

**Comment by trvswgnr** [comment] 2023-04-15 04:38
thanks for staying on top of replies @TCROC.

for anyone who doesn't understand the value at this point, i will update the website soon and hopefully provide some clarity. otherwise https://github.com/crablang/crab/issues/14#issuecomment-1508776721 does a pretty good job explaining.

**Comment by dunxen** [comment] 2023-04-15 10:49
On the website it states:

> By offering a community-driven alternative, we hope to maintain a spirit of collaboration, innovation, and creative freedom.

As I understand this within the context of “innovation”, it seems that divergence from upstream Rust is being encouraged, but at the same time “main will track upstream Rust”.

Also, beyond this, I still see a lot of confusion for newcomers to Rust. Seems to be at odds with “not fracturing the community”. There’ll also be more confusion with the distinction between the Rust project and the Rust Foundation. 

Just thoughts, but I know I hazard some tribalism in replies. 😅

**Comment by cbeuw** [comment] 2023-04-15 22:46
> With our shared passion for programming, we welcome anyone interested to join us in exploring the Crab community fork. Whether or not you fully agree with our concerns, we believe that diversity of thought and a commitment to inclusivity will only strengthen our collective efforts. 
> https://crablang.org/

A noble and agreeable goal for sure, tough I'm not certain that it's being faithfully implemented. I was banned from the Discord server without warning after disagreeing with an accusation a CrabLang admin made about a current Rust contributor. IIRC I wrote 4 messages on Discord in total since I joined yesterday - the first two lead to an improvement in the wording of the Trademark section of CrabLang's README, and the last two got me banned.

I'm not here to appeal my ban. I'm not interested in pursuing that disagreement either - I was told that I'm wrong by the admin seconds before the ban, so maybe I was wrong, big deal.

I would say though, if you want to command the confidence of a community that you are capable of shepherding them, you need to have a better moderation standard. It should appear non-arbitrary to the programmer on the Clapham Omnibus. It must bind everyone equally - maybe you wished to forbid non-technical discussions (because you just want to do cool computer stuff), but then the project leaders must set an example and _not_ instigate off-hand remarks in a public channel. And finally, if someone does stray from constructive discussion, [assume good faith](https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith) nudge them back, ban hammer should be the last resort (except for obvious bots and spammers) - I'm sure this is the way [Rust moderation](https://manishearth.github.io/blog/2019/02/04/rust-governance-scaling-empathy/) is carried out. By this rate CrabLang might end up banning more people than communities with CoCs that's apparently unsavoury to many here.

I don't have this confidence in the CrabLang leaders.

I still think this project could be technically interesting because ripping out a trademarked name from a Free Software codebase is an open problem in Open Source. This is a [long standing question](https://google.github.io/opencasebook/trademarks/), including in the context of Rust many years before the current controversies with the Foundation. If CrabLang manages to do this while staying well-synced with upstream, the experience could prove useful to other projects if their trademark holder go rogue, or if people simply want to distribute an exploratory fork. But as I said, I don't think the CrabLang leadership can command the confidence of enough talented people to do this long term. I don't matter because I'm a nobody, but eventually you will lose people who matter.

**Comment by trvswgnr** [comment] 2023-04-16 01:56
> On the website it states:
> 
> > By offering a community-driven alternative, we hope to maintain a spirit of collaboration, innovation, and creative freedom.
> 
> As I understand this within the context of “innovation”, it seems that divergence from upstream Rust is being encouraged, but at the same time “main will track upstream Rust”.
> 
> Also, beyond this, I still see a lot of confusion for newcomers to Rust. Seems to be at odds with “not fracturing the community”. There’ll also be more confusion with the distinction between the Rust project and the Rust Foundation.
> 
> Just thoughts, but I know I hazard some tribalism in replies. 😅

we discourage dog-piling in general, but especially when you have a genuine question or concern 😊

the main branch will—aside from some superficial changes—mirror the upstream repo. 

features and changes to the codebase are really a moot point at this time; there is a lot to do before we concern ourselves with any of that. in the context provided, "innovation" refers more to finding creative ways to solve the challenges ahead of us.

hope that helps!

**Comment by trvswgnr** [comment] 2023-04-16 02:06
hi @cbeuw, im very sorry we've made you lose confidence in us and our ability to shepherd this project. i'm not sure of the details surrounding your being banned from the discord, but i know there are some types of behavior that we simply do not tolerate. i also understand that emotions have been running high lately for all of us; some people have been coming into the server with the sole purpose of getting a rise out of the members. if you'd like me to look into why you were banned and/or if you would like to come back, please don't hesitate to reach out to me.

we want to foster a good relationship with the community and don't discourage different opinions, as long as the goal isn't to shout and offend as much as possible.

we're really proud of all the great ideas and effort our little corner of the community has put into this project, and we hope you'll see that we want nothing but a friendly, open space for discussion of our favorite topics.

also thanks so much for your help with the readme/trademark section; i don't think you're a nobody ☺️

**Comment by trvswgnr** [comment] 2023-04-19 06:06
@zigster64 we have longer term goals, yes. every programmer has gripes with their favorite language, and we have had a lot of great ideas and input. our primary goal right now is to have stable branch that's up-to-date. after that we can start an experimental branch that will act as a playground for some of the community's more creative and ambitious ideas.

**Comment by zigster64** [comment] 2023-04-20 00:40
> @zigster64 we have longer term goals, ...

OK, that's pretty cool then, thanks for the well thought out reply.

There are some good technical ideas behind the compiler toolchain, and it would be nice to see a properly technical project to build on those ideas to make better dev tools.  

Sort of - for programmers, by programmers, minus all the politics.
That would definitely be worth supporting.

**Comment by Churchexe** [comment] 2023-04-25 12:04
"instead of taking community control of the project and distancing the project from the people who just proposed some of the most overbearing trademark rules ever, even exceeding that of companies like Oracle in some areas, we should instead just politely ask them to stop and leave the fate of the project in their hands entirely and just trusting they'll all magically have a change of heart and pull a 180 than a white jewel themed antagonist from a children's TV show."

Yes, forking always brings challenges, but when the only alternative you can propose is just sit and wait for them to "DO BETTER SENATOR" when they straightfaced proposed something as overbearing as they did, not really a compelling argument. I, for one, will happily be an armed crablang developer with a notably non-robust CoC.

**Comment by JiveyGuy** [comment] 2023-04-25 21:03
I was talking in the Tauri discord and my main point is you simply need to navigate to [Rust Foundation: Members](https://foundation.rust-lang.org/members/ ) to see where their moral alignment is. 

Some of their members have aided governments in tracking down dissidents who speak out against genocides. 

[They really did that.](https://www.businessinsider.com/huawei-built-more-surveillance-tools-to-track-uyghurs-report-2020-12)

**Comment by elliott-sh** [comment] 2023-05-28 21:09
-1

**Closed** 2023-06-11 13:08 UTC

**Comment by luisnquin** [comment] 2023-06-28 04:48
+1
