### ISSUE TITLE
Use .cr file extension

### ISSUE THREAD

**Issue by o-agassizii** [crablang/crab#31] opened 2023-04-17 19:21 UTC
The original language that should not be named uses .rs as its file extension.

Crablang should use .cr as file extension.

Incidentally, there exists a .cr TLD.

So in the same way that people have been using .rs TLD with the original language that should not be named. https://en.wikipedia.org/wiki/.rs

Users of Crablang could use the .cr TLD. https://en.wikipedia.org/wiki/.cr

**Comment by rilysh** [comment] 2023-04-17 21:11
You can't use `.cr` as file extension as it's already taken by Crystal Language, see https://en.m.wikipedia.org/wiki/Crystal_(programming_language

Personally, I think it should be right to just use `.rs` until a better idea comes in mind. No need to hurry as the drafted CoC hasn't been officially approved yet. It also may make it harder to keep synchronised with Rust upstream changes.

**Comment by TCROC** [comment] 2023-04-18 03:16
We are discussing over here: https://github.com/crablang/crab/issues/20

@trvswgnr i think u can mark this as duplicate

**Comment by mjovanc** [comment] 2023-04-18 10:17
It's much better with `.crab`as @TCROC started an issue previously regarding.

**Comment by hamza72x** [comment] 2023-04-18 23:21
No, keeping `.rs` will allow compiling the existing codebases? Just asking.

**Comment by trvswgnr** [comment] 2023-04-19 00:59
correct, @hamza72x any changes to the file extension will have to be on the experimental branch.

duplicate of #20, closing this 😊

**Closed by trvswgnr** 2023-04-19 00:59 UTC

**Comment by TCROC** [comment] 2023-04-19 03:35
> No, keeping `.rs` will allow compiling the existing codebases? Just asking.

@hamza72x I addressed this same question over here :)

https://github.com/crablang/crab/issues/20#issuecomment-1513561036
